uploads = []
generated = []

[[outputs]]
id = "s30RUf7Uxtwd0m1GW1fOd"
uri = "file://screenshots/wolfxnode-landing.jpg"
type = "image"
title = "wolfXnode — Hero Only"

[[outputs]]
id = "RJEHwdy2EVx-HyInf2mhN"
uri = "file://screenshots/wolfxcore-landing.jpg"
type = "image"
title = "wolfXcore — Game Server Management Panel"

[[outputs]]
id = "9vQl_HHOJ56Stw_lCzryR"
uri = "file://screenshots/wolfxbase-hero.jpg"
type = "image"
title = "wolfXbase — MongoDB Management Dashboard"

[[outputs]]
id = "D5mSUMXmgS641u0NNDqib"
uri = "file://screenshots/wolfxapis-hero.jpg"
type = "image"
title = "wolfXapis — Multi-Provider API Hub"
